# Generated by Django 4.2.27 on 2026-06-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf_templates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdfbrandingprofile",
            name="template",
            field=models.CharField(
                choices=[
                    ("modern", "Executive"),
                    ("minimal", "Minimal"),
                    ("corporate", "Corporate"),
                    ("classic", "Classic"),
                    ("vivid", "Vivid"),
                    ("elegant", "Elegant"),
                ],
                default="modern",
                max_length=20,
            ),
        ),
    ]
