# Generated by Django 4.2.27 on 2026-01-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("RENT", "Rent"),
                            ("UTILITY", "Utility"),
                            ("SERVICE", "Service Fee"),
                            ("PENALTY", "Late Penalty"),
                        ],
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(db_index=True)),
                ("due_date", models.DateField(db_index=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("VOID", "Void"),
                            ("OVERDUE", "Overdue"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="tenants.contract",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="UtilityBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY", "Electricity"),
                            ("WATER", "Water"),
                            ("AC", "A/C (BTU)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "previous_reading",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "current_reading",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("consumption", models.DecimalField(decimal_places=2, max_digits=12)),
                ("rate_per_unit", models.DecimalField(decimal_places=4, max_digits=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("reading_date", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="utility_readings",
                        to="billing.invoice",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="utility_bills",
                        to="properties.unit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_date", models.DateField(db_index=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("TRANSFER", "Bank Transfer"),
                            ("CHECK", "Check"),
                            ("CASH", "Cash"),
                            ("POS", "Point of Sale"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True,
                        help_text="Check number or Transaction identifier",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
        ),
    ]
