# Generated by Django 4.2.27 on 2026-01-10 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cheque_number", models.CharField(max_length=50)),
                ("bank_name", models.CharField(max_length=100)),
                ("drawer_name", models.CharField(blank=True, max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "cheque_date",
                    models.DateField(
                        help_text="The date written on the cheque (Due Date)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received (In Hand)"),
                            ("DEPOSITED", "Deposited"),
                            ("CLEARED", "Cleared (Collected)"),
                            ("BOUNCED", "Bounced (Returned)"),
                            ("RETURNED_BY_US", "Returned to Tenant"),
                        ],
                        default="RECEIVED",
                        max_length=20,
                    ),
                ),
                (
                    "cheque_image",
                    models.FileField(
                        blank=True,
                        help_text="Scanned copy of the cheque",
                        null=True,
                        upload_to="cheques/",
                    ),
                ),
                ("cleared_date", models.DateField(blank=True, null=True)),
                ("bounced_date", models.DateField(blank=True, null=True)),
                ("bounce_reason", models.CharField(blank=True, max_length=255)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cheques",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cheque",
                "verbose_name_plural": "Cheques",
                "ordering": ["cheque_date"],
            },
        ),
    ]
