# Generated by Django 4.2.27 on 2026-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_cheque"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="proof_document",
            field=models.FileField(blank=True, null=True, upload_to="payments/%Y/%m/"),
        ),
    ]
