# Generated by Django 4.2.19 on 2026-01-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_payment_proof_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheque",
            name="deposit_image",
            field=models.FileField(
                blank=True,
                help_text="Bank deposit slip",
                null=True,
                upload_to="deposits/",
            ),
        ),
    ]
