# Generated by Django 4.2.19 on 2026-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_cheque_deposit_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Internal notes or additional comments"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_for",
            field=models.CharField(
                blank=True,
                help_text="Description of what is being paid for (As Payment Of)",
                max_length=255,
            ),
        ),
    ]
