# Generated by Django 4.2.19 on 2026-01-20 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_payment_notes_payment_payment_for"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Rent, Utility, Service Fee",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_type",
            field=models.CharField(max_length=50),
        ),
    ]
