# Generated by Django 4.2.19 on 2026-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_invoicetype_alter_invoice_invoice_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Custom description for the PDF (Description / البيان)",
                max_length=255,
            ),
        ),
    ]
