# Generated by Django 4.2.27 on 2026-01-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_invoice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="knowledge_tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Amount of Knowledge Tax (ضريبة المعارف) for this invoice",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="knowledge_tax_paid",
            field=models.BooleanField(
                default=False,
                help_text="Whether the Knowledge Tax has been paid to the municipality",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="knowledge_tax_paid_date",
            field=models.DateField(
                blank=True, help_text="Date when Knowledge Tax was paid", null=True
            ),
        ),
    ]
