# Generated by Django 4.2.27 on 2026-06-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("billing", "0010_invoice_notes_invoicelineitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="properties.building",
            ),
        ),
    ]
