# Generated by Django 4.2.27 on 2026-06-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("billing", "0012_backfill_building"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoicetype",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="invoicetype",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_types",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="invoicetype",
            name="name",
            field=models.CharField(
                help_text="e.g. Rent, Utility, Service Fee", max_length=100
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoicetype",
            unique_together={("building", "name")},
        ),
    ]
