# Generated by Django 4.2.27 on 2026-01-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MAINTENANCE", "Maintenance"),
                            ("UTILITIES", "Common Utilities"),
                            ("MANAGEMENT", "Management Fees"),
                            ("TAXES", "Taxes & Gov Fees"),
                            ("CLEANING", "Cleaning"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("expense_date", models.DateField(db_index=True)),
                (
                    "invoice_reference",
                    models.CharField(
                        blank=True, help_text="Vendor Invoice Number", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="properties.building",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="If expense is specific to a unit",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date"],
            },
        ),
    ]
