# Generated by Django 4.2.27 on 2026-01-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_expensecategory_alter_expense_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="expenses/%Y/%m/"),
        ),
    ]
