# Generated by Django 4.2.19 on 2026-01-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0003_expense_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="expense_for",
            field=models.CharField(
                blank=True,
                help_text="Custom description for the PDF (As Expense Of)",
                max_length=255,
            ),
        ),
    ]
