# Generated by Django 4.2.27 on 2026-06-15 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("expenses", "0004_expense_expense_for"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expensecategory",
            options={"ordering": ["name"], "verbose_name_plural": "Expense Categories"},
        ),
        migrations.AddField(
            model_name="expense",
            name="cost_type",
            field=models.CharField(
                choices=[
                    ("DYNAMIC", "Dynamic (one-off)"),
                    ("FIXED", "Fixed (recurring)"),
                ],
                db_index=True,
                default="DYNAMIC",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expensecategory",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expense_categories",
                to="properties.building",
            ),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="expensecategory",
            unique_together={("building", "name")},
        ),
        migrations.CreateModel(
            name="FixedCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vendor_name", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMIANNUAL", "Semi-annual"),
                            ("YEARLY", "Yearly"),
                            ("CUSTOM", "Custom interval"),
                        ],
                        default="MONTHLY",
                        max_length=12,
                    ),
                ),
                (
                    "custom_interval",
                    models.PositiveIntegerField(
                        blank=True, help_text="For CUSTOM frequency", null=True
                    ),
                ),
                (
                    "custom_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DAY", "Days"),
                            ("WEEK", "Weeks"),
                            ("MONTH", "Months"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(db_index=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional: stop generating after this date",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_costs",
                        to="properties.building",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_costs",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_costs",
                        to="properties.unit",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name"],
            },
        ),
        migrations.CreateModel(
            name="FixedCostOccurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        db_index=True, help_text="The period this occurrence covers"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expense",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixed_cost_occurrence",
                        to="expenses.expense",
                    ),
                ),
                (
                    "fixed_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="expenses.fixedcost",
                    ),
                ),
            ],
            options={
                "ordering": ["period_date"],
                "unique_together": {("fixed_cost", "period_date")},
            },
        ),
    ]
