# Generated by Django 4.2.19 on 2026-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_file",
            field=models.FileField(
                blank=True,
                help_text="Signed contract PDF",
                null=True,
                upload_to="contracts/",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="payment_frequency",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("BIANNUALLY", "Bi-Annually"),
                    ("YEARLY", "Yearly"),
                    ("CUSTOM", "Custom Schedule"),
                ],
                max_length=20,
            ),
        ),
    ]
