# Generated by Django 4.2.19 on 2026-01-13 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_contract_contract_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="tax_number",
            field=models.CharField(
                blank=True, help_text="Tax Identification Number", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="national_id",
            field=models.CharField(
                blank=True, help_text="National ID / Passport Number", max_length=50
            ),
        ),
        migrations.CreateModel(
            name="TenantDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.FileField(upload_to="tenants/docs/%Y/%m/")),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="tenants.tenant",
                    ),
                ),
            ],
        ),
    ]
