# Generated by Django 4.2.27 on 2026-06-15 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
        ("tenants", "0003_tenant_tax_number_alter_tenant_national_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="properties.building",
            ),
        ),
    ]
