# Generated by Django 4.2.27 on 2026-01-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField()),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Total square meters", max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Ground Floor, Floor 1", max_length=50
                    ),
                ),
                ("number", models.IntegerField(help_text="For sorting purposes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="properties.building",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=50)),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("COMMERCIAL", "Commercial"),
                            ("RETAIL", "Retail"),
                        ],
                        default="RESIDENTIAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VACANT", "Vacant"),
                            ("OCCUPIED", "Occupied"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("RESERVED", "Reserved"),
                        ],
                        db_index=True,
                        default="VACANT",
                        max_length=20,
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2, help_text="Square meters", max_digits=10
                    ),
                ),
                (
                    "market_rent",
                    models.DecimalField(
                        decimal_places=2, help_text="Target rental price", max_digits=12
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="properties.floor",
                    ),
                ),
            ],
            options={
                "ordering": ["unit_number"],
                "unique_together": {("floor", "unit_number")},
            },
        ),
        migrations.AddIndex(
            model_name="floor",
            index=models.Index(
                fields=["building", "number"], name="properties__buildin_4fe179_idx"
            ),
        ),
    ]
