# Generated by Django 4.2.27 on 2026-01-08 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField(db_index=True)),
                ("description", models.CharField(max_length=255)),
                (
                    "account_name",
                    models.CharField(
                        db_index=True,
                        help_text="e.g., Accounts Receivable, Bank, Rental Income",
                        max_length=100,
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="properties.building",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Ledger Entries",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="accounting__content_656b23_idx",
                    ),
                    models.Index(
                        fields=["transaction_date"],
                        name="accounting__transac_52297b_idx",
                    ),
                    models.Index(
                        fields=["account_name"], name="accounting__account_35eb36_idx"
                    ),
                ],
            },
        ),
    ]
